### PR TITLE
fix: add barrel file

### LINKED ISSUE #130: Missing (dist) index.js which exports all matchers for library usage
### Relevant code or config:

```js
const jestNativeMatchers = require('@testing-library/jest-native')
```
### What you did:

Upgrade `@testing-library/jest-native` from `4.0.2` to `5.3.0`

### What happened:

`Cannot find module '@testing-library/jest-native ...`

### Reproduction:

Try to import all or individual matchers using the code example in the README.md.

### Problem description:

After inspecting the package, the `main` entry field in `package.json` points to a `dist/index.js`, which doesn't exist. 

### Suggested solution:

Re-add the barrel file (dist/index.js) to export the matchers. You can automate this part of the build too using [barrelsby](https://github.com/bencoveney/barrelsby).

### Can you help us fix this issue by submitting a pull request?

Yes, I could help submit a PR. I wanted to log the issue first to see if this is intended 😄

### PR DESCRIPTION
**Pull request by jgornick**
**What**:

Re-added barrel file in src directory. Also added npm script (`generate-barrels`).
Resolves #130 

**Why**:

Unable to import matchers for use in a library.

**How**:

Used barrelsby to generate barrel file.

**Checklist**:

- [X] Documentation added to the [docs](https://github.com/testing-library/jest-native/README.md)
- [X] Typescript definitions updated
- [X] Tests
- [X] Ready to be merged

### CODE REVIEW

**Comment by jgornick** [comment]
Bump ^^^

cc @mdjastrzebski

**Comment by mdjastrzebski** [comment]
@jgornick  Would adding src/index.ts alone resolve your issue? I am wary about including additional deps like barelsby if not strictly needed.

**Comment by mdjastrzebski** [comment]
Removed barrelsby dep, but kept the src/index.ts file.

**Comment by jgornick** [comment]
I'm sorry for not following up on this @mdjastrzebski. I appreciate you though doing the work and getting it merged in!

**Pull request merged**
