### PR TITLE
fix: change extend-expect types definition to support explicit jest globals

### PR DESCRIPTION
**Pull request by alexamy**
**What**:

Change matchers type definitions to support explicit jest globals import from `@jest/globals` module.

**Why**:

If you are using explicit jest globals, matchers interface is imported from `@jest/expect` and has slightly different structure, so current solution (extending matchers interface in global namespace) isn't applicable.

**How**:

Matchers interface has been extracted to avoid duplication. Both Jest matchers interfaces (for explicit and implicit globals) are extended.

**Checklist**:

- [x] Documentation added to the [docs](https://github.com/testing-library/jest-native/README.md) (N/A)
- [x] Typescript definitions updated
- [x] Tests
- [x] Ready to be merged 

Fixes https://github.com/testing-library/jest-native/issues/136.

### CODE REVIEW

**Comment by mdjastrzebski** [comment]
@alexamy Is it possible to add tests (in TS sense, to be validated by TSC and by not by running Jest) that would check these two cases? It would be good idea to have them in the repo.

**Comment by alexamy** [comment]
Actually I thought about the same thing! I'll see if I can do something
(`ExpectType`, etc). Thanks for the suggestion!

сб, 17 дек. 2022 г., 01:35 Maciej Jastrzebski ***@***.***>:

**Comment by alexamy** [comment]
Added the types tests, which must be checked with `tsc`:
- Add `__types__` directory for testing types and [test file](https://github.com/testing-library/jest-native/pull/137/files#diff-26d03ea165b725772de4989a5f12fc74f6a48e85baee231e65f0402a41d95707)
- Add `__types__` directory to [jest ignore patterns](https://github.com/testing-library/jest-native/pull/137/files#diff-1e058ca1442e46581b13571fb8d261f9e1f5657e26c96634d4c1072f0f0347f1R7-R13)

How to check that test is working locally:
In `extend-expect.d.ts` try to remove interface extensions: [implicit](https://github.com/testing-library/jest-native/blob/fc6b6490fa91a6a0723eaa0f95ce5ab1022c20d6/extend-expect.d.ts#L24-L29), [explicit](https://github.com/testing-library/jest-native/blob/fc6b6490fa91a6a0723eaa0f95ce5ab1022c20d6/extend-expect.d.ts#L32-L34). You will see types error, e.g.:
image

There are no type errors in this test for this PR.

**Comment by alexamy** [comment]
Rewrote type tests with more generic expect and generics in test queries.

**Comment by mdjastrzebski** [comment]
@alexamy thank you for patience, I've had quite a busy time before Christmas. 

You've done a great work researching the issue and providing solution. 
From my part I've tweaked the tests to rely on actual `expect` usage rather than type calculations.

**Pull request merged**
