### PR TITLE
chore: upgrade to Jest 27

### PR DESCRIPTION
**Pull request by nickmccurdy**
**What**: Upgrade to Jest 27

**Why**: Ensuring compatibility with breaking changes in Jest 27

**How**: Upgrading packages

**Checklist**:

- [ ] Documentation added to the
      [docs](https://github.com/testing-library/jest-native/README.md) (N/A)
- [ ] Typescript definitions updated (N/A)
- [x] Tests
- [x] Ready to be merged

### CODE REVIEW

**Review by thymikee — APPROVED** [review]
I'm surprised there's no lock file in this repo. Feel free to add yarn.lock :)

**Comment by nickmccurdy** [comment]
As far as I'm aware, it's a trend of this organization to not use lockfiles for packages, so I'd rather stay consistent personally. If you still want a lockfile, I can add one for npm, since this organization tends to use npm over Yarn.

**Comment by thymikee** [comment]
Meh, ok, I don't care this much. What's up with Travis not reporting status? Maybe a fresh commit helps

**Comment by nickmccurdy** [comment]
I think it's because this repository was still using the legacy service integration for Travis, which has been removed. I've reinstalled the app for this repository. Let's see if it builds. If not, I'll replace it with GitHub Actions.

**Comment by thymikee** [comment]
Looks like it didn't help. Let's move to GH Actions then, thanks for offering help in that :)

**Review by brunohkbx — APPROVED** [review]

**Pull request merged**
