### PR TITLE
feat(breaking): toHaveTextContent supports nested arrays of sibling elements

### PR DESCRIPTION
**Pull request by philipbulley**
BREAKING CHANGE: toHaveTextContent may produce more output in some cases due to including all nested sibling elements

**What**:

`toHaveTextContent` currently supports recursion, but it would only handle the first child element of a deeply nested child.

This existing test would of course pass:
https://github.com/testing-library/jest-native/blob/master/src/__tests__/to-have-text-content.js#L50-L63

But add a sibling element to the nested `View` and it would fail to include the ` additional text ` of said element. In this example, it would receive: `Step 1 4`

```js
<Text testID="parent">
  <Text>Step</Text>
  <Text> 1 </Text>
  <View>
    <Text> of </Text>
    <Text> additional text </Text> // <-- toHaveTextContent would never parse this 
  </View>
  4
</Text>
```

**Why**:

`toHaveTextContent` should parse all nested elements including siblings, not just the first child of a nested element.

**How**:

When the element being parsed is an array, loop through the array and recursively use `getText` to retrieve its text content.

**Checklist**:

- [x] Documentation added to the
      [docs](https://github.com/testing-library/jest-native/README.md)
- [ ] Typescript definitions updated (N/A)
- [x] Tests
- [x] Ready to be merged 

**Please note:**
I've flagged this as a breaking change due to the possibility that there may be tests out in the wild that have ignored the fact that `toHaveTextContent` didn't return the full text of all descendant elements. But if you feel that it's very much an edge case, then I'd be happy to recategorise this as a fix/patch.

### CODE REVIEW

**Comment by philipbulley** [comment]
Hey @thymikee, just wondering if anyone is available to review this PR? Thanks! 🙂

**Comment by thymikee** [comment]
Will have a look next week

**Review by thymikee — APPROVED** [review]
Looks good!

**Pull request merged**
