### PR TITLE
test: snapshot toHaveStyle diff output

### PR DESCRIPTION
**Pull request by philipbulley**
**What**:

Reimplement the snapshot tests for `toHaveStyle`

**Why**:

See discussion here:
https://github.com/testing-library/jest-native/commit/f0f434643b3b54da7be242660dc4a34b5efc9cfa#r42121221

**tl;dr** @brunohkbx discovered a problem running the tests with snapshots as part of #26 , so let's isolate this change to more effectively debug. Testing the output diff is important as it's key feedback users rely on when a test fails.

**Checklist**:

- [ ] Documentation added to the
      [docs](https://github.com/testing-library/jest-native/README.md) (N/A)
- [ ] Typescript definitions updated (N/A)
- [x] Tests
- [x] Ready to be merged

### CODE REVIEW

**Comment by philipbulley** [comment]
@brunohkbx looking at the original snapshot failure, it appears that the chalk annotations weren't showing up in the received result (https://travis-ci.org/github/testing-library/jest-native/jobs/724947397#L231). Everything else looked good. Let's see what happens after this is merged. 👍🏽

**Comment by thymikee** [comment]
Or we can switch to CircleCI. Travis is (was?) known to have different color output when running Jest on master vs any other branch. We had issues like that in Jest repo and eventually migrated off of Travis.

**Comment by brunohkbx** [comment]
@thymikee seems like jest has an option to force color highlight. Take a look [--colors](https://jestjs.io/docs/en/cli#--colors)

**Comment by thymikee** [comment]
Whatever works 👍

**Comment by brunohkbx** [comment]
It worked :tada:

**Pull request merged**
